name: Unsplash
favicon: null
layout_spectrum: 0.8585013397969306
typography_spectrum: 0.6640260864514858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.7593408240936697
purpose:
  - name: awareness
    item: null
    url: null
